DROP TABLE IF EXISTS users;

CREATE TABLE users(
  id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
  
  full_name VARCHAR(80),
  email VARCHAR(80),
  password VARCHAR(80),
	
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NULL,
  
  PRIMARY KEY (id)
);


-- CREATE TABLE users(
  -- id INT GENERATED ALWAYS AS IDENTITY NOT NULL,
  -- full_name VARCHAR(80) NOT NULL
  -- email VARCHAR(80) UNIQUE NOT NULL,
  -- password VARCHAR(80) NOT NULL,
  --   created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  -- updated_at TIMESTAMP DEFAULT NULL,
    
--   PRIMARY KEY (id)
-- );