CREATE TABLE users(
  id int AUTO_INCREMENT NOT NULL,
  
  full_name VARCHAR(80),
  email VARCHAR(80),
  password VARCHAR(80),
	
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY (id)
);


-- CREATE TABLE users(
--   id int AUTO_INCREMENT NOT NULL,
  -- full_name VARCHAR(80) NOT NULL
--   email VARCHAR(80) UNIQUE NOT NULL,
--   password VARCHAR(80) NOT NULL,
-- 	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
--   updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    
--   PRIMARY KEY (id)
-- );